apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-guardian.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ default "controller" .Values.controller.serviceAccount.name }}
  namespace: {{ include "kube-guardian.namespace" . }}
roleRef:
  kind: ClusterRole
  name: kube-guardian
  apiGroup: rbac.authorization.k8s.io
