---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  namespace: kube-guardian
  labels:
    app: postgresdb
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: 5432
      # targetPort: postgresdb
      protocol: TCP
      name: http
  selector:
    app: postgresdb
---
# TODO This resource should be a statefulset
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      automountServiceAccountToken: true
      containers:
        - name: postgresdb
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: rust
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_DB
              value: kube
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
      volumes:
        - name: db-data
          {{- if .Values.database.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.database.persistence.claimName }}
          {{- else }}
          emptyDir: {}
          {{- end -}}
