apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-guardian.name" . }}-broker
  labels:
    {{- include "kube-guardian.labels" . | nindent 4 }}
  annotations:
    {{- include "kube-guardian.annotations" . | nindent 4 }}
spec:
  {{- if not .Values.broker.autoscaling.enabled }}
  replicas: {{ .Values.broker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.broker.service.name }}
      app.kubernetes.io/name: {{ .Values.broker.service.name }}
  template:
    metadata:
      {{- with .Values.broker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.broker.service.name }}
        app.kubernetes.io/name: {{ .Values.broker.service.name }}
    spec:
      {{- with .Values.broker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ default "broker" .Values.broker.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.broker.podSecurityContext | nindent 8 }}
      containers:
        - name: broker
          securityContext:
            {{- toYaml .Values.broker.securityContext | nindent 12 }}
          image: "{{ .Values.broker.image.repository }}:{{ .Values.broker.image.tag }}"
          imagePullPolicy: {{ .Values.broker.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.broker.container.port }}
              protocol: TCP
          env:
            - name: DB_ENDPOINT
              value: "postgres://rust@{{ .Values.database.name }}.{{ include "kube-guardian.namespace" . }}.svc.cluster.local:{{ .Values.database.container.port }}/kube"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
         {{- with .Values.broker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.broker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
