---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  namespace: kube-guardian
  labels:
    app: postgresdb
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: 5432
      # targetPort: postgresdb
      protocol: TCP
      name: http
  selector:
    app: postgresdb
