{{- if .Values.broker.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "broker" .Values.broker.serviceAccount.name }}
  labels:
    {{- include "kube-guardian.labels" . | nindent 4 }}
  {{- with .Values.broker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.broker.serviceAccount.automountServiceAccountToken }}
{{- end }}
